def manual_redaing(manual):
    with open(manual,"a+") as file:
        file.write("        Welcome To The Raza's Transportation system\n\n\n")
        file.write("For Customers Guide:\n")
        file.write("1. First You Need To Sign Up For Using Our Services.\n")
        file.write("2. After Sign Up You Can Login And Use Our Services.\n")
        file.write("3. You Can Book A Vehicle For Your Desired Days.\n")
        file.write("4. You Can View Your Previous Booking History.\n")
        file.write("5. You Can Exit From Program.\n\n\n")
        file.write("For Members Guide:\n")
        file.write("1. First You Need To Sign Up For Using Our Services.\n")
        file.write("2. After Sign Up You Can Login And Use Our Services.\n")
        file.write("3. You Can Share Your Vehicle For Booking.\n")
        file.write("4. You Can View All Your Vehicles That You set for Booking.\n")
        file.write("5. You Can Update Your Vehicles Information.\n")
        file.write("6. You Can Exit From Program.\n\n\n")
        file.write("For Admin Guide:\n")
        file.write("1. You Can Login And Use Our Services.\n")
        file.write("3. You Can View All Users Information.\n")
        file.write("4. You Can View All Vehicles Information.\n")
        file.write("5. You Can Update Users Information.\n")
        file.write("6. You Can Update Vehicles Information.\n")
        file.write("7. You Can Exit From Program.\n\n\n")
        file.seek(0)
        contents=file.read()
        print(contents)

